[package]
name = "web_hazard_project"
version = "0.1.1"
edition = "2021"

[lib]
name = "web_hazard_project"
crate-type = ["cdylib"]

[dependencies]
pyo3 = { version = "^0.27.2", features = ["extension-module"] }
